version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports: 
      - '5432:5432'
    volumes:
      - gqlapp-db:/var/lib/postgresql/data

  gqlapp:
    build:
      context: .
    environment:
      DB_SCHEMA: postgres
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: postgres
    depends_on:
      - postgres
    ports:
      - '4000:4000'

volumes:
  gqlapp-db:
